### ISSUE TITLE
Banshee V0.4 Assertion Fail

### ISSUE THREAD

**Issue by carlosmarti** [BearishSun/BansheeEngine#49] opened 2016-09-29 14:44 UTC
I'm getting a C++ Assertion Failed when i run the Editor. At first i thought it was when creating a folder in the Resources. That does not seem to be the case as i just started the Editor and it gave me the Assertion Failed window again. This is what the windows says.

Running this on Windows 10 64-bit
![bansh](https://cloud.githubusercontent.com/assets/5507549/18958735/86735296-8618-11e6-8e40-52f450b9ff1a.PNG)

**Comment by BearishSun** [comment] 2016-09-29 14:56
Hi. Are you running the pre-compiled binaries or did you compile yourself?

**Comment by carlosmarti** [comment] 2016-09-29 14:58
Yeah this is the pre-compiled binaries from the website.

**Comment by BearishSun** [comment] 2016-09-29 15:15
I'm aware of the origin of the issue. I'll try to provide a potential fix for you in a bit.

**Comment by BearishSun** [comment] 2016-09-29 15:39
I uploaded new binaries with a potential fix: http://bearishsun.thalassa.feralhosting.com/Banshee%20Editor.zip. 

Note that I cannot reproduce the issue on my end, so I cannot confirm it works.

**Comment by carlosmarti** [comment] 2016-09-29 16:28
Unfortunately that did not fix the issue. It's the same problem but this time it's saying that it's on line 481 on the same file. The only thing that i'm doing is on start up i move the project manager around and i get that Assertion Failed.

**Comment by BearishSun** [comment] 2016-09-29 18:26
Alright, I'll get back to you when I have a chance to investigate further.

**Comment by BearishSun** [comment] 2016-09-30 20:25
If you run the binaries I uploaded yesterday, and hit Abort when the error happens, there should be a crash log generated in the CrashLogs directory (next to the editor executable). Can you send me the log? Don't run the original binaries as they won't contain the necessary information.

Also, what's your CPU?

**Comment by carlosmarti** [comment] 2016-09-30 21:48
Is it the binary that you uploaded here? because that's the one i'm using. I hit abort but there is no crash log next to the executable of the program. This happens with both of my computers 

Desktop spec:
CPU: Intel core i5 3470
GPU: GTX 660 TI
MOBO: MSI

Laptop:
CPU: AMD A-10

**Comment by BearishSun** [comment] 2016-09-30 21:52
Ah sorry, try hitting Retry instead and then check for log. If that doesn't do it I'll upload another binary.

**Comment by carlosmarti** [comment] 2016-09-30 22:34
Ok here you go. I have never seen a game engine create a log like that. It's pretty cool.
![log](https://cloud.githubusercontent.com/assets/5507549/19008890/6028d51e-8723-11e6-9b23-adc672a8bac2.PNG)

**Comment by BearishSun** [comment] 2016-09-30 22:39
Thanks! This helps to narrow down the issue a bit, but I'll need more time to properly investigate.

**Comment by carlosmarti** [comment] 2016-09-30 23:02
Take your time. I don't want to be a nuisance but i found another crash. I'm try'n to break it to see what i can find to let you know. The new crash has to do with moving the tabs. I haven't been able to reproduce but if i get to reproduce again should i open a new issue?

**Comment by BearishSun** [comment] 2016-10-01 10:50
Yeah definitely open a new issue, any reported bug is helpful!

**Comment by BearishSun** [comment] 2016-10-10 15:02
Hi, sorry for taking a while to get around to this. I uploaded a new build: http://bearishsun.thalassa.feralhosting.com/BansheeEditor_Test.zip

Try running it and let me know if that changes anything.

**Comment by carlosmarti** [comment] 2016-10-10 16:51
The editor crashed at the beginning this is the report that it created. 
![log](https://cloud.githubusercontent.com/assets/5507549/19243985/134227f6-8ecf-11e6-95ba-570348d6a0be.PNG)

**Comment by BearishSun** [comment] 2016-10-10 17:31
Try this one: http://bearishsun.thalassa.feralhosting.com/BansheeEditor_Test2.zip

**Comment by carlosmarti** [comment] 2016-10-10 19:38
Unfortunately it doesn't look like it was fixed. I'm still getting the same error.
![log](https://cloud.githubusercontent.com/assets/5507549/19248723/7e9ba542-8ee6-11e6-9d23-61a0591432b6.PNG)

**Comment by BearishSun** [comment] 2016-10-10 19:53
Alright thanks, at least this confirms I was looking at the wrong place. I'll keep digging.

**Comment by BearishSun** [comment] 2016-10-17 08:20
This should now be fixed in e8175f03bf98f08ec0b2dd87cedce4a4ad5398ac! When you get a chance try running the binaries to confirm the fix works: http://bearishsun.thalassa.feralhosting.com/BansheeEditor_v0.4p1.zip

**Comment by carlosmarti** [comment] 2016-10-17 12:52
That seems to have done it. I have used it for a little while and this assertion has not come up.

**Comment by BearishSun** [comment] 2016-10-17 14:56
Great, closing the issue.

**Closed by BearishSun** 2016-10-17 14:56 UTC
