### ISSUE TITLE
[EDITOR] Crash on start - Failed to open OpenAL device

### ISSUE THREAD

**Issue by 690fps** [BearishSun/BansheeEngine#233] opened 2018-07-14 05:04 UTC
I downloaded Editor binaries v0.4.0 (Windows x64)
Can't start BansheeEditorExec.exe on 2 systems:
- Win 7 SP1 - i3 7100 + 1050ti
- Win 10.0 LTSB - i3 5010U

VS2015 and VS2017 redistributables are installed

There is an error in crash reports: 
```
InternalErrorException - Failed to open OpenAL device: 
in __cdecl BansheeEngine::OAAudio::OAAudio(void) [C:\Projects\BansheeEngineDev\BansheeEngine\Source\BansheeOpenAudio\Source\BsOAAudio.cpp:66]
```
Crash reports and system detailes:
[Win 7 SP1 - i3 7100 + 1050ti.zip](https://github.com/BearishSun/BansheeEngine/files/2194661/Win.7.SP1.-.i3.7100.%2B.1050ti.zip)
[Win 10.0 LTSB - i3 5010U.zip](https://github.com/BearishSun/BansheeEngine/files/2194662/Win.10.0.LTSB.-.i3.5010U.zip)

**Comment by BearishSun** [comment] 2018-07-14 06:22
Hi. All reported issues need to be reproducible on the latest master build. v0.4.0 release is very old and quite likely this issue was already resolved.

**Comment by BearishSun** [comment] 2018-07-18 09:45
Closing due to old version it occurred on. If the issue still persists on master feel free to reopen the issue.

**Closed by BearishSun** 2018-07-18 09:45 UTC
