### ISSUE TITLE
[Generation / BansheeSL] --wincompat not a switch available in Git-bundled flex

### ISSUE THREAD

**Issue by DW01** [BearishSun/BansheeEngine#158] opened 2018-01-17 13:37 UTC
CMakeLists.txt for BansheeSL sets an option for flex that doesn't seem to be present in the build packaged with Git for Windows (`--wincompat`). This made CMake not generate project files.

I ran `flex.exe --help` for confirmation, [and sure enough, the option isn't present](https://i.imgur.com/ejMGJim.png).

**Comment by BearishSun** [comment] 2018-01-17 13:55
Banshee comes with its own version of flex, present in `Dependencies/tools/flex`. What error message did CMake produce when generating project files?

**Comment by DW01** [comment] 2018-01-17 14:00
`"C:/Program Files (x86)/Git/bin/flex.exe": 
Unrecognized option `--wincompat'
Try `flex.exe" --help' for more information.`

What seems to be happening is that CMake detected the wrong flex installation and is using Git's flex rather than Banshee's. Lot's of weird CMake behavior today!

**Comment by BearishSun** [comment] 2018-01-17 14:07
Indeed, although this one is probably a bug in Banshee's build system. Can you try adding this line to `Source/CMake/Modules/Findflex.cmake`:

`find_program(flex_EXECUTABLE NAMES flex bin/flex PATHS ${flex_INSTALL_DIRS} NO_DEFAULT_PATH)`

It should be added right before the existing `find_program` command, so it looks like this:

`find_program(flex_EXECUTABLE NAMES flex bin/flex PATHS ${flex_INSTALL_DIRS} NO_DEFAULT_PATH)
find_program(flex_EXECUTABLE NAMES flex bin/flex PATHS ${flex_INSTALL_DIRS})`

It should hopefully force CMake to look in local folders before searching globally. Note that you might need to clear cmake cache (or delete the build folder), as CMake tends to cache these variables and wont update them if it's just ran again normally.

**Comment by DW01** [comment] 2018-01-17 14:18
That did the trick!

Previously, I just manually changed the Flex executable path in the advanced build options, but that's probably not ideal long-term.

**Comment by BearishSun** [comment] 2018-01-17 14:20
Nice. Since you confirmed it works, I committed a fix in ada88ff618c389d07bacbd70f1b2b4d545bceb45. Closing the issue.

**Closed by BearishSun** 2018-01-17 14:20 UTC
