### ISSUE TITLE
Crash in editor when i add a “Distance Joint” component.

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#200] opened 2018-04-18 07:31 UTC
when i add  a compoent(Distance Joint), the editor crash .

**Comment by BearishSun** [comment] 2018-04-18 08:39
I'll check it out, but in case I cannot reproduce the problem it would be helpful if you can upload the error log that's generated when the crash happens.

**Comment by XMatrixXiang** [comment] 2018-04-18 09:58
![crash](https://user-images.githubusercontent.com/13548583/38925397-17820cdc-4332-11e8-869e-209743467388.png)

**Comment by XMatrixXiang** [comment] 2018-04-18 09:59
here is the crashReports
[20180418_1754.zip](https://github.com/BearishSun/BansheeEngine/files/1923425/20180418_1754.zip)

**Comment by BearishSun** [comment] 2018-04-18 11:51
Thanks, I'll take a look as soon as I get a chance.

**Comment by XMatrixXiang** [comment] 2018-04-18 12:59
Thank you for your attention.

**Comment by BearishSun** [comment] 2018-04-20 13:39
This issue is now resolved in the latest revision. Note that I haven't tested other aspects of physics joints so if you encounter a crash at some other point let me know.

**Closed by BearishSun** 2018-04-20 13:39 UTC

**Comment by XMatrixXiang** [comment] 2018-04-21 08:10
Thanks , Checked and it's good 。
but 
how to set Anchor and Target property  for Distance Joint in editor?  
i do not know how to drag and drop a rigid body component to that .

**Comment by BearishSun** [comment] 2018-04-22 11:29
There was an issue with component drag and drop. I've fixed it in the latest revision. You should now be able to just drag an object from the Hierarchy view onto the relevant field, and it will pick up the Rigidbody component.
