### ISSUE TITLE
[EDITOR - LIGHTS] Crash when exiting the application if a light is being deleted. 

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#147] opened 2018-01-15 04:23 UTC
Hi, 

I just remarked that If I delete a light, the lighting of it is still present and If I close the application there is a crash.

**Comment by BearishSun** [comment] 2018-01-15 08:59
I managed to reproduce the issue where deleted lights remain on the screen, and it should be fixed with b88991e052a57843a445324da634937e2bdf236c. 

I have't managed to reproduce the crash on shutdown, and it's unlikely to be caused by the issue I resolved. Possibly it's a separate problem. If you have a crash log, or have steps/project with which you can reproduce it consistently let me know.

**Comment by christianclavet** [comment] 2018-01-15 15:52
Retested and now the light no longer light the wall when deleted (as it should), and there is no crash when I close the application. The crash must have been the rigidbody component that I was not able to remove from the scene.

**Closed** 2018-01-15 17:13 UTC
