### ISSUE TITLE
Not building on Linux: BansheeEngine/Source/BansheeSL/BsParserFX.h No such file or directory

### ISSUE THREAD

**Issue by drequivalent** [BearishSun/BansheeEngine#103] opened 2017-11-12 20:40 UTC
```
-- Building BSL lexer/parser...
/home/equivalent/banshee/BansheeEngine/Dependencies/tools/bison/bin/bison: /home/bearishsun/Projects/Banshee/Dependencies/bison-3.0/build/install/share/bison/m4sugar/m4sugar.m4: cannot open: No such file or directory
CMake Error at BansheeSL/CMakeLists.txt:19 (file):
  file RENAME failed to rename

    /home/equivalent/banshee/BansheeEngine/Source/BansheeSL/BsParserFX.h

  to

    /home/equivalent/banshee/BansheeEngine/Source/BansheeSL/BsParserFX.h

  because: No such file or directory



CMake Error at BansheeSL/CMakeLists.txt:20 (file):
  file RENAME failed to rename

    /home/equivalent/banshee/BansheeEngine/Source/BansheeSL/BsParserFX.c

  to

    /home/equivalent/banshee/BansheeEngine/Source/BansheeSL/BsParserFX.c

  because: No such file or directory



-- Looking for XShaderCompiler installation...
-- ...XShaderCompiler OK.
-- Looking for Mono compiler (mcs) and xbuild installation...
-- ...mcs and xbuild OK.
-- Configuring incomplete, errors occurred!
See also "/home/equivalent/banshee/BansheeEngine/Build/CMakeFiles/CMakeOutput.log".
```

**Comment by BearishSun** [comment] 2017-11-13 10:32
Thanks for the report, somehow this slipped by me. I've reproduced the problem and it is resolved with 287a89d8605e6debbce9fb241198646a96286c0d. Bison executable apparently doesn't like to be redistributed to using non-standard install paths.

Please note that I've updated the compile steps, and as an additional requirement you will need to manually install flex & bison packages for your distro (.e.g. *apt-get install bison flex* on Debian/Ubuntu).

**Closed by BearishSun** 2017-11-13 10:32 UTC

**Comment by drequivalent** [comment] 2017-11-16 23:37
Now, the error on make:
```
In file included from /home/equivalent/banshee/BansheeEngine/Source/BansheeCore/./Profiling/BsProfilerCPU.h:7:0,
                 from /home/equivalent/banshee/BansheeEngine/Source/BansheeCore/Profiling/BsProfilerCPU.cpp:3:
/home/equivalent/banshee/BansheeEngine/Source/BansheeCore/../BansheeUtility/Allocators/BsFrameAlloc.h: In instantiation of ‘T* bs::FrameAlloc::alloc(Args&& ...) [with T = std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >; Args = {bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>}]’:
/home/equivalent/banshee/BansheeEngine/Source/BansheeCore/Profiling/BsProfilerCPU.cpp:184:46:   required from here
/home/equivalent/banshee/BansheeEngine/Source/BansheeCore/../BansheeUtility/Allocators/BsFrameAlloc.h:80:67: error: no matching function for call to ‘std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >::stack(bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>)’
    return new ((T*)alloc(sizeof(T))) T(std::forward<Args>(args)...);
                                                                   ^
In file included from /usr/include/c++/5/stack:61:0,
                 from /home/equivalent/banshee/BansheeEngine/Source/BansheeCore/../BansheeUtility/Allocators/BsMemStack.h:5,
                 from /home/equivalent/banshee/BansheeEngine/Source/BansheeCore/../BansheeUtility/Allocators/BsMemoryAllocator.h:440,
                 from /home/equivalent/banshee/BansheeEngine/Source/BansheeCore/../BansheeUtility/Prerequisites/BsPrerequisitesUtil.h:262,
                 from /home/equivalent/banshee/BansheeEngine/Source/BansheeCore/./BsCorePrerequisites.h:5,
                 from /home/equivalent/banshee/BansheeEngine/Source/BansheeCore/./Profiling/BsProfilerCPU.h:5,
                 from /home/equivalent/banshee/BansheeEngine/Source/BansheeCore/Profiling/BsProfilerCPU.cpp:3:
/usr/include/c++/5/bits/stl_stack.h:141:7: note: candidate: std::stack<_Tp, _Sequence>::stack(_Sequence&&) [with _Tp = bs::ProfilerCPU::ActiveBlock; _Sequence = std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> >]
       stack(_Sequence&& __c = _Sequence())
       ^
/usr/include/c++/5/bits/stl_stack.h:141:7: note:   no known conversion for argument 1 from ‘bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>’ to ‘std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> >&&’
/usr/include/c++/5/bits/stl_stack.h:137:7: note: candidate: std::stack<_Tp, _Sequence>::stack(const _Sequence&) [with _Tp = bs::ProfilerCPU::ActiveBlock; _Sequence = std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> >]
       stack(const _Sequence& __c)
       ^
/usr/include/c++/5/bits/stl_stack.h:137:7: note:   no known conversion for argument 1 from ‘bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>’ to ‘const std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> >&’
/usr/include/c++/5/bits/stl_stack.h:99:11: note: candidate: std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >::stack(const std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >&)
     class stack
           ^
/usr/include/c++/5/bits/stl_stack.h:99:11: note:   no known conversion for argument 1 from ‘bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>’ to ‘const std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >&’
/usr/include/c++/5/bits/stl_stack.h:99:11: note: candidate: std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >::stack(std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >&&)
/usr/include/c++/5/bits/stl_stack.h:99:11: note:   no known conversion for argument 1 from ‘bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>’ to ‘std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >&&’
BansheeCore/CMakeFiles/BansheeCore.dir/build.make:374: recipe for target 'BansheeCore/CMakeFiles/BansheeCore.dir/Profiling/BsProfilerCPU.cpp.o' failed
make[2]: *** [BansheeCore/CMakeFiles/BansheeCore.dir/Profiling/BsProfilerCPU.cpp.o] Error 1
CMakeFiles/Makefile2:211: recipe for target 'BansheeCore/CMakeFiles/BansheeCore.dir/all' failed
make[1]: *** [BansheeCore/CMakeFiles/BansheeCore.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by BearishSun** [comment] 2017-11-17 07:11
This error is caused by an older version of the C++ standard library that doesn't support custom allocators for `std::stack`. My guess is you are using an older version of the library (and the compiler). Banshee requires at least GCC 7.
