### ISSUE TITLE
Adding a new output to GBuffer

### ISSUE THREAD

**Issue by dragonCASTjosh** [BearishSun/BansheeEngine#64] opened 2017-01-12 00:34 UTC
I am trying to add a new output to the GBuffer to handle the PBR texture data like roughness and metallic. but in adding a new buffer I have shader compile errors.

I have added the buffer into Reader Beast using the albedo buffer A as my guide on what is needed where. Note i am passing in 1 texture for PBR, that is because I'm compressing roughness and metallic into 1 texture.

I will paste the HLSL11 part of the shader and the error in the console.

GBuffer.bslinc
```
Technique : base("GBuffer") =
{
	Language = "HLSL11";

	Pass =
	{
		Common = 
		{
			struct GBufferData
			{
				float4 albedo;
				float4 worldNormal;
				float4 pbr;
				float depth;
			};
			
			void encodeGBuffer(GBufferData data, out float4 GBufferAData, out float4 GBufferBData, out float4 GBufferCData)
			{
				GBufferAData = data.albedo;
				GBufferBData.xyz = float3(data.worldNormal.xyz * 0.5f + 0.5f);
				GBufferBData.w = 1.0f; // Marks that some deferred data was written
				GBufferCData = data.pbr;
			}
		};
	};
};

```

DeferredLightPass.bslinc
```
Parameters =
{
	Sampler2D 	gGBufferASamp : alias("gGBufferATex");
	Sampler2D 	gGBufferBSamp : alias("gGBufferBTex");
	Sampler2D 	gGBufferCSamp : alias("gGBufferCTex");
	Sampler2D 	gDepthBufferSamp : alias("gDepthBufferTex");
	
	Texture2D 	gGBufferATex : auto("GBufferA");
	Texture2D	gGBufferBTex : auto("GBufferB");
	Texture2D	gGBufferCTex : auto("GBufferC");
	Texture2D 	gDepthBufferTex : auto("GBufferDepth");
};

Blocks =
{
	Block PerCamera : auto("PerCamera");
	Block PerLight : auto("PerLight");
};

Technique
 : base("DeferredLightPass")
 : inherits("GBuffer")
 : inherits("PerCameraData") =
{
	Language = "HLSL11";
	
	Pass =
	{
		Target = 
		{
			Blend = true;
			Color = { ONE, ONE, ADD };
			WriteMask = RGB;
		};
		
		DepthWrite = false;

		Common = 
		{
			#define PI 3.1415926
			#define HALF_PI 1.5707963
			
			cbuffer PerLight
			{
				// x, y, z - World position of the lightData
				// w - Type type - Directional = 0, Point = >0, Spot = >0.5
				float4 gLightPositionAndType;
				float4 gLightColorAndIntensity;
				// x - outerAngle in radians, y - cos(outerAngle), z - 1.0f/(cos(innerAngle) - cos(outerAngle)), w - inverse point light radius
				float4 gLightSpotAnglesAndSqrdInvRadius;
				float3 gLightDirection;
				
				// x - Num sides (zero for point lights)
				// y - Num slices (zero for point lights)
				// z - Sphere radius for point lights
				// w - Cone radius for spot lights
				float4 gLightGeometry; 
				float4x4 gMatConeTransform;
			}
			
			struct LightData
			{
				float3 position;
				float3 direction;
				float intensity;
				bool isSpot;
				bool isPoint;
				float3 spotAngles; 
				float3 color;
				float radiusSqrdInv;
			};
			
			float convertFromDeviceZ(float deviceZ)
			{
				return (1.0f / (deviceZ + gDeviceZToWorldZ.y)) * gDeviceZToWorldZ.x;
			}
			
			GBufferData decodeGBuffer(float4 GBufferAData, float4 GBufferBData, float4 GBufferCData, float deviceZ)
			{
				GBufferData output;
				
				output.albedo.xyz = GBufferAData.xyz;
				output.albedo.w = 1.0f;
				output.worldNormal = GBufferBData * float4(2, 2, 2, 1) - float4(1, 1, 1, 0);
				output.worldNormal.xyz = normalize(output.worldNormal.xyz);
				output.depth = convertFromDeviceZ(deviceZ);
				output.pbr = GBufferCData;
				
				return output;
			}
			
			LightData getLightData()
			{
				LightData output;
				
				output.position = gLightPositionAndType.xyz;
				output.direction = gLightDirection;
				output.color = gLightColorAndIntensity.rgb;
				output.intensity = gLightColorAndIntensity.w;
				output.isPoint = gLightPositionAndType.w > 0.0f;
				output.isSpot = gLightPositionAndType.w > 0.5f;
				output.spotAngles = gLightSpotAnglesAndSqrdInvRadius.xyz;
				output.radiusSqrdInv = gLightSpotAnglesAndSqrdInvRadius.w;
				
				return output;
			}
			
			float getSpotAttenuation(float3 worldPosToLight, float3 direction, float3 angles)
			{
				float output = saturate((dot(-worldPosToLight, direction) - angles.y) * angles.z);
				return output * output;
			}			
			
			float4 getLighting(float3 worldPosition, float2 uv, GBufferData gBuffer, LightData lightData)
			{
				float3 N = gBuffer.worldNormal.xyz;
				float NoL = 1.0f;
				
				float distanceAttenuation = 1.0f;
				float spotFalloff = 1.0f;
				float radiusAttenuation = 1.0f;
				if (lightData.isPoint)
				{
					float3 L = lightData.position - worldPosition;
					
					float distanceSqrd = dot(L, L);
					distanceAttenuation = 1/(distanceSqrd + 1);
					
					L = normalize(L);
					NoL = saturate(dot(N, L)); // TODO - Add bias here?

					radiusAttenuation = distanceSqrd * lightData.radiusSqrdInv;
					radiusAttenuation *= radiusAttenuation;
					radiusAttenuation = saturate(1.0f - radiusAttenuation);
					radiusAttenuation *= radiusAttenuation;
					
					if (lightData.isSpot)
						spotFalloff = getSpotAttenuation(L, lightData.direction, lightData.spotAngles);
				}
				else
				{
					float3 L = -lightData.direction;
					NoL = saturate(dot(N, L)); // TODO - Add bias here?
				}

				float attenuation = distanceAttenuation * spotFalloff * radiusAttenuation;

				float3 diffuse = gBuffer.albedo.xyz / PI; // TODO - Add better lighting model later

				float4 output = float4(lightData.color * lightData.intensity * ((NoL * attenuation) * diffuse), 1);
				return output;
			}
		};
		
		Fragment = 
		{
			SamplerState 	gGBufferASamp : register(s0);
			SamplerState 	gGBufferBSamp : register(s1);
			SamplerState 	gGBufferCSamp : register(s2);
			SamplerState 	gDepthBufferSamp : register(s3);
	
			Texture2D 	gGBufferATex : register(t0);
			Texture2D	gGBufferBTex : register(t1);
			Texture2D	gGBufferCTex : register(t2);
			Texture2D 	gDepthBufferTex : register(t3);
			
			GBufferData getGBufferData(float2 uv)
			{
				float4 GBufferAData = gGBufferATex.SampleLevel(gGBufferASamp, uv, 0);
				float4 GBufferBData = gGBufferBTex.SampleLevel(gGBufferBSamp, uv, 0);
				float4 GBufferCData = gGBufferCTex.SampleLevel(gGBufferCSamp, uv, 0);
				float deviceZ = gDepthBufferTex.SampleLevel(gDepthBufferSamp, uv, 0).r;
				
				return decodeGBuffer(GBufferAData, GBufferBData, GBufferCData, deviceZ);
			}			
		};	
	};
};
```

Diffuse.bsl
```
Parameters =
{
	Sampler2D 	gAlbedoSamp : alias("gAlbedoTex");
	Sampler2D 	gNormalSamp : alias("gNormalTex");
	Sampler2D   gPBRSamp  : alias("gPbrTex");
	
	Texture2D 	gAlbedoTex;
	Texture2D	gNormalTex = "normal";
	Texture2D   gPbrTex  = "pbr";
};

Technique : base("Surface") =
{
	Language = "HLSL11";
	
	Pass =
	{
		Fragment =
		{
			SamplerState gAlbedoSamp : register(s0);
			SamplerState gNormalSamp : register(s1);
			SamplerState gPBRSamp  : register(s2);
			
			Texture2D gAlbedoTex : register(t0);
			Texture2D gNormalTex : register(t1);
			Texture2D gPbrTex  : register(t2);

			float4 main(
				in VStoFS input, 
				out float4 OutGBufferA : SV_Target1,
				out float4 OutGBufferB : SV_Target2,
				out float4 OutGBufferC : SV_Target3) : SV_Target0
			{
				float3 normal = normalize(gNormalTex.Sample(gNormalSamp, input.uv0) * 2.0f - float3(1, 1, 1));
				float3 worldNormal = calcWorldNormal(input, normal);
			
				GBufferData gbufferData;
				gbufferData.albedo = gAlbedoTex.Sample(gAlbedoSamp, input.uv0);
				gbufferData.worldNormal.xyz = worldNormal;
				gbufferData.pbr = gPbrTex.Sample(gPBRSamp, input.uv0);
				
				encodeGBuffer(gbufferData, OutGBufferA, OutGBufferB, OutGBufferC);
				
				// TODO - Just returning a simple ambient term, use better environment lighting later
				return float4(gbufferData.albedo.rgb, 1.0f) * 0.01f; 
			}	
		};
	};
};
```

Error
```

Error while parsing shader FX code "D:\EmberEngine\Data\Raw\Engine\Shaders\Default.bsl":
Failed compiling GPU program(s): Fragment program: Cannot compile D3D11 high-level shader. Errors:
D:\EmberEngine\Build\VS2015\BansheeEditorExec\Shader@0x0000026C41388BB0(10,102-113): error X3508: 'encodeGBuffer': output parameter 'GBufferCData' not completely initialized


Line 9: 			void encodeGBuffer(GBufferData data, out float4 GBufferAData, out float4 GBufferBData, out float4 GBufferCData)
Fragment program: Cannot compile D3D11 high-level shader. Errors:
D:\EmberEngine\Build\VS2015\BansheeEditorExec\Shader@0x0000026C413D92A0(10,102-113): error X3508: 'encodeGBuffer': output parameter 'GBufferCData' not completely initialized


Line 9: 			void encodeGBuffer(GBufferData data, out float4 GBufferAData, out float4 GBufferBData, out float4 GBufferCData)
Fragment program: Cannot compile D3D11 high-level shader. Errors:
D:\EmberEngine\Build\VS2015\BansheeEditorExec\Shader@0x0000026C413D4C70(10,102-113): error X3508: 'encodeGBuffer': output parameter 'GBufferCData' not completely initialized


Line 9: 			void encodeGBuffer(GBufferData data, out float4 GBufferAData, out float4 GBufferBData, out float4 GBufferCData)
Fragment program: Cannot compile D3D11 high-level shader. Errors:
D:\EmberEngine\Build\VS2015\BansheeEditorExec\Shader@0x0000026C414546E0(10,102-113): error X3508: 'encodeGBuffer': output parameter 'GBufferCData' not completely initialized


Line 9: 			void encodeGBuffer(GBufferData data, out float4 GBufferAData, out float4 GBufferBData, out float4 GBufferCData)
. Location: 0 (0)

		 in class std::shared_ptr<class bs::Resource> __cdecl bs::SLImporter::import(const class bs::Path &,class std::shared_ptr<class bs::ImportOptions const >) [d:\emberengine\source\bansheesl\source\bsslimporter.cpp:54]
Trying to import asset that doesn't exists. Asset path: D:\EmberEngine\Data\Raw\Engine\Skin\StatusBarBackground.png

		 in class std::shared_ptr<class bs::ImportOptions> __cdecl bs::Importer::createImportOptions(const class bs::Path &) [d:\emberengine\source\bansheecore\source\bsimporter.cpp:161]
Trying to import asset that doesn't exists. Asset path: D:\EmberEngine\Data\Raw\Engine\Skin\StatusBarBackground.png

		 in class bs::TResourceHandle<class bs::Resource,0> __cdecl bs::Importer::import(const class bs::Path &,class std::shared_ptr<class bs::ImportOptions const >,const class std::basic_string<char,struct std::char_traits<char>,class bs::StdAlloc<char,class bs::GenAlloc> > &) [d:\emberengine\source\bansheecore\source\bsimporter.cpp:59]
'BansheeEditorExec.exe' (Win32): Loaded 'D:\EmberEngine\bin\x64\Debug\BansheeMono.dll'. Symbols loaded.
'BansheeEditorExec.exe' (Win32): Loaded 'D:\EmberEngine\bin\x64\Debug\mono-2.0.dll'. Symbols loaded.
'BansheeEditorExec.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. Cannot find or open the PDB file.
Cannot find texture parameter with the name 'gGBufferCTex'

		 in void __cdecl bs::TGpuParams<1>::getTextureParam(enum bs::GpuProgramType,const class std::basic_string<char,struct std::char_traits<char>,class bs::StdAlloc<char,class bs::GenAlloc> > &,class bs::TGpuParamTexture<1> &) const [d:\emberengine\source\bansheecore\source\bsgpuparams.cpp:312]
Cannot find texture parameter with the name 'gGBufferCTex'

		 in void __cdecl bs::TGpuParams<1>::getTextureParam(enum bs::GpuProgramType,const class std::basic_string<char,struct std::char_traits<char>,class bs::StdAlloc<char,class bs::GenAlloc> > &,class bs::TGpuParamTexture<1> &) const [d:\emberengine\source\bansheecore\source\bsgpuparams.cpp:312]
'BansheeEditorExec.exe' (Win32): Loaded 'D:\EmberEngine\bin\x64\Debug\SBansheeEngine.dll'. Symbols loaded.
Cannot find texture parameter with the name 'gGBufferCTex'

		 in void __cdecl bs::TGpuParams<1>::getTextureParam(enum bs::GpuProgramType,const class std::basic_string<char,struct std::char_traits<char>,class bs::StdAlloc<char,class bs::GenAlloc> > &,class bs::TGpuParamTexture<1> &) const [d:\emberengine\source\bansheecore\source\bsgpuparams.cpp:312]
'BansheeEditorExec.exe' (Win32): Loaded 'D:\EmberEngine\bin\x64\Debug\SBansheeEditor.dll'. Symbols loaded.

```

**Comment by BearishSun** [comment] 2017-01-12 08:48
Hey! I think your shaders are fine, the problem is there is another shader called "Default.bsl" which uses the GBuffer functions you modified, and that one is failing. You just need to change it same as you changed Diffuse.bsl and you should be good to go.

**Comment by dragonCASTjosh** [comment] 2017-01-12 13:30
i did make changes to Default.bsl

```
Technique : base("Surface") =
{
	Language = "HLSL11";
	
	Pass =
	{
		Fragment =
		{
			float4 main(
				in VStoFS input, 
				out float4 OutGBufferA : SV_Target1,
				out float4 OutGBufferB : SV_Target2,
				out float4 OutGBufferC : SV_Target3) : SV_Target0
			{
				GBufferData gbufferData;
				gbufferData.albedo = float4(0.05f, 0.05f, 0.05f, 1.0f);
				gbufferData.worldNormal.xyz = input.tangentToWorldZ;
				gbufferData.pbr.x = 0.5f;
				gbufferData.pbr.y = 0.0f;
								
				encodeGBuffer(gbufferData, OutGBufferA, OutGBufferB, OutGBufferC);
				
				// TODO - Just returning a simple ambient term, use better environment lighting later
				return float4(gbufferData.albedo.rgb, 1.0f); 
			}	
		};
	};
};
```

**Comment by BearishSun** [comment] 2017-01-12 13:55
You're writing to x/y components of the pbr portion of the GBuffer:
```
gbufferData.pbr.x = 0.5f;
gbufferData.pbr.y = 0.0f;
```

But not to z/w. That seems to be what the error is complaining about.

`'encodeGBuffer': output parameter 'GBufferCData' not completely initialized`

**Comment by dragonCASTjosh** [comment] 2017-01-12 13:58
Ok so it now seems the initial error was solved. But now im left with 
```
Cannot find texture parameter with the name 'gGBufferCTex'
```

**Comment by BearishSun** [comment] 2017-01-12 14:09
The shader looks fine and like it should be able to find that parameter. Try deleting Data/Engine/Timestamp.asset which will force all shaders to reimport the next time you run the engine in debug mode, in case its incorrectly using some older version of the shader.

**Comment by dragonCASTjosh** [comment] 2017-01-12 14:14
Hmm i delete that and its till there. It seams to only be a warning and it appears in the editor log console with more details 
```
in void __cdecl bs::TGpuParams<1>::getTextureParam(enum bs::GpuProgramType,const class std::basic_string<char,struct std::char_traits<char>,class bs::StdAlloc<char,class bs::GenAlloc> > &,class bs::TGpuParamTexture<1> &) const [d:\emberengine\source\bansheecore\source\bsgpuparams.cpp:312]
Cannot find texture parameter with the name 'gGBufferCTex'
```

**Comment by BearishSun** [comment] 2017-01-12 14:28
It is a warning but it means that the texture you're assigning to gGBufferCTex won't get assigned.

The only other place I can think of the error being, is that getTextureParam is getting called on a different shader that doesn't have that parameter. When are you calling it? In BsLightRendering.cpp same as other gbuffer textures? Can you post that code snipped?

You can also try to debug yourself by putting a breakpoint in D3D11GpuProgram::initialize(). It will get called for every shader so it might be a hassle to find the one you're looking for (DeferredLightPass.bslinc). You can check by reading the source code.

Once you do trigger a breakpoint for the correct shader, you can dig into the populateParametersAndConstants method, to see which uniforms are detected and if gGBufferCTex is there.

**Comment by dragonCASTjosh** [comment] 2017-01-12 14:43
Is this the section of code you are looking for
```
LightRenderingParams::LightRenderingParams(const SPtr<Material>& material, const SPtr<GpuParamsSet>& paramsSet)
		:mMaterial(material), mParamsSet(paramsSet)
	{
		SPtr<GpuParams> params = mParamsSet->getGpuParams();

		auto& texParams = material->getShader()->getTextureParams();
		for (auto& entry : texParams)
		{
			if (entry.second.rendererSemantic == RPS_GBufferA)
				params->getTextureParam(GPT_FRAGMENT_PROGRAM, entry.second.name, mGBufferA);
			else if (entry.second.rendererSemantic == RPS_GBufferB)
				params->getTextureParam(GPT_FRAGMENT_PROGRAM, entry.second.name, mGBufferB);
			else if (entry.second.rendererSemantic == RPS_GBufferC)
				params->getTextureParam(GPT_FRAGMENT_PROGRAM, entry.second.name, mGBufferC);
			else if (entry.second.rendererSemantic == RPS_GBufferDepth)
				params->getTextureParam(GPT_FRAGMENT_PROGRAM, entry.second.name, mGBufferDepth);
		}

		mParamBuffer = gPerLightParamDef.createBuffer();
		mParamsSet->setParamBlockBuffer("PerLight", mParamBuffer, true);
	}

	void LightRenderingParams::setStaticParameters(const SPtr<RenderTargets>& gbuffer, 
		const SPtr<GpuParamBlockBuffer>& perCamera)
	{
		mGBufferA.set(gbuffer->getTextureA());
		mGBufferB.set(gbuffer->getTextureB());
		mGBufferC.set(gbuffer->getTextureC());
		mGBufferDepth.set(gbuffer->getTextureDepth());

		mParamsSet->setParamBlockBuffer("PerCamera", perCamera, true);

		gRendererUtility().setPassParams(mParamsSet);
	}
```

**Comment by dragonCASTjosh** [comment] 2017-01-12 15:55
So following through the code i know it triggers on line 312 of BsGpuParams.cpp and paramDescs->textures is length of 3 not the length of 4 it needs to be. Any ideas

**Comment by BearishSun** [comment] 2017-01-12 16:02
Like I mentioned before you'll need to put a breakpoint in D3D11GpuProgram::initialize(). Then dig into populateParametersAndConstants() method, and also check the shader source under D3D11GpuProgram::mProperties to see if it's valid. This method will trigger for every single shader, so you'll need to figure out when it triggers for the one you're interested in, and ignore the others.

That's the point where param descs object GpuParams is using, is being populated. By stepping through that code you should be able to figure out why that specific uniform isn't getting registered.

**Comment by dragonCASTjosh** [comment] 2017-01-13 14:29
The best I can narrow it down at the moment is line 34 in D3D11HLSLParamParser::parse is only returning 3 inputs. it's the first place something seems to be different to what I would expect. I can't seem to go under that level as it is within the DirectX lib.

![inputs](https://cloud.githubusercontent.com/assets/3044415/21933147/1f0c6214-d99c-11e6-8a60-1f0e0c636089.PNG)

Here is a copy of the shader source from within the debugger:
```

			struct GBufferData
			{
				float4 albedo;
				float4 worldNormal;
				float4 pbr;
				float depth;
			};
			
			void encodeGBuffer(GBufferData data, out float4 GBufferAData, out float4 GBufferBData, out float4 GBufferCData)
			{
				GBufferAData = data.albedo;
				GBufferBData.xyz = float3(data.worldNormal.xyz * 0.5f + 0.5f);
				GBufferBData.w = 1.0f; // Marks that some deferred data was written
				GBufferCData = data.pbr;
			}
		
			cbuffer PerCamera
			{
				float3	 gViewDir;
				float3 	 gViewOrigin;
				float4x4 gMatViewProj;
				float4x4 gMatView;
				float4x4 gMatProj;
				float4x4 gMatInvProj;
				float4x4 gMatInvViewProj;
				float4x4 gMatScreenToWorld;
				float2 	 gDeviceZToWorldZ;
				float4 	 gClipToUVScaleOffset;				
			}
		
			#define PI 3.1415926
			#define HALF_PI 1.5707963
			
			cbuffer PerLight
			{
				// x, y, z - World position of the lightData
				// w - Type type - Directional = 0, Point = >0, Spot = >0.5
				float4 gLightPositionAndType;
				float4 gLightColorAndIntensity;
				// x - outerAngle in radians, y - cos(outerAngle), z - 1.0f/(cos(innerAngle) - cos(outerAngle)), w - inverse point light radius
				float4 gLightSpotAnglesAndSqrdInvRadius;
				float3 gLightDirection;
				
				// x - Num sides (zero for point lights)
				// y - Num slices (zero for point lights)
				// z - Sphere radius for point lights
				// w - Cone radius for spot lights
				float4 gLightGeometry; 
				float4x4 gMatConeTransform;
			}
			
			struct LightData
			{
				float3 position;
				float3 direction;
				float intensity;
				bool isSpot;
				bool isPoint;
				float3 spotAngles; 
				float3 color;
				float radiusSqrdInv;
			};
			
			float convertFromDeviceZ(float deviceZ)
			{
				return (1.0f / (deviceZ + gDeviceZToWorldZ.y)) * gDeviceZToWorldZ.x;
			}
			
			GBufferData decodeGBuffer(float4 GBufferAData, float4 GBufferBData, float4 GBufferCData, float deviceZ)
			{
				GBufferData output;
				
				output.albedo.xyz = GBufferAData.xyz;
				output.albedo.w = 1.0f;
				output.worldNormal = GBufferBData * float4(2, 2, 2, 1) - float4(1, 1, 1, 0);
				output.worldNormal.xyz = normalize(output.worldNormal.xyz);
				output.depth = convertFromDeviceZ(deviceZ);
				output.pbr = GBufferCData;
				
				return output;
			}
			
			LightData getLightData()
			{
				LightData output;
				
				output.position = gLightPositionAndType.xyz;
				output.direction = gLightDirection;
				output.color = gLightColorAndIntensity.rgb;
				output.intensity = gLightColorAndIntensity.w;
				output.isPoint = gLightPositionAndType.w > 0.0f;
				output.isSpot = gLightPositionAndType.w > 0.5f;
				output.spotAngles = gLightSpotAnglesAndSqrdInvRadius.xyz;
				output.radiusSqrdInv = gLightSpotAnglesAndSqrdInvRadius.w;
				
				return output;
			}
			
			float getSpotAttenuation(float3 worldPosToLight, float3 direction, float3 angles)
			{
				float output = saturate((dot(-worldPosToLight, direction) - angles.y) * angles.z);
				return output * output;
			}			
			
			float4 getLighting(float3 worldPosition, float2 uv, GBufferData gBuffer, LightData lightData)
			{
				float3 N = gBuffer.worldNormal.xyz;
				float NoL = 1.0f;
				
				float distanceAttenuation = 1.0f;
				float spotFalloff = 1.0f;
				float radiusAttenuation = 1.0f;
				if (lightData.isPoint)
				{
					float3 L = lightData.position - worldPosition;
					
					float distanceSqrd = dot(L, L);
					distanceAttenuation = 1/(distanceSqrd + 1);
					
					L = normalize(L);
					NoL = saturate(dot(N, L)); // TODO - Add bias here?

					radiusAttenuation = distanceSqrd * lightData.radiusSqrdInv;
					radiusAttenuation *= radiusAttenuation;
					radiusAttenuation = saturate(1.0f - radiusAttenuation);
					radiusAttenuation *= radiusAttenuation;
					
					if (lightData.isSpot)
						spotFalloff = getSpotAttenuation(L, lightData.direction, lightData.spotAngles);
				}
				else
				{
					float3 L = -lightData.direction;
					NoL = saturate(dot(N, L)); // TODO - Add bias here?
				}

				float attenuation = distanceAttenuation * spotFalloff * radiusAttenuation;

				float3 diffuse = gBuffer.albedo.xyz / PI; // TODO - Add better lighting model later

				float4 output = float4(lightData.color * lightData.intensity * ((NoL * attenuation) * diffuse), 1);
				return output;
			}
		
			struct VStoFS
			{
				float4 position : SV_POSITION;
				float2 uv0 : TEXCOORD0;
				float3 screenDir : TEXCOORD1;
			};
		
			SamplerState 	gGBufferASamp : register(s0);
			SamplerState 	gGBufferBSamp : register(s1);
			SamplerState 	gGBufferCSamp : register(s2);
			SamplerState 	gDepthBufferSamp : register(s3);
	
			Texture2D 	gGBufferATex : register(t0);
			Texture2D	gGBufferBTex : register(t1);
			Texture2D	gGBufferCTex : register(t2);
			Texture2D 	gDepthBufferTex : register(t3);
			
			GBufferData getGBufferData(float2 uv)
			{
				float4 GBufferAData = gGBufferATex.SampleLevel(gGBufferASamp, uv, 0);
				float4 GBufferBData = gGBufferBTex.SampleLevel(gGBufferBSamp, uv, 0);
				float4 GBufferCData = gGBufferCTex.SampleLevel(gGBufferCSamp, uv, 0);
				float deviceZ = gDepthBufferTex.SampleLevel(gDepthBufferSamp, uv, 0).r;
				
				return decodeGBuffer(GBufferAData, GBufferBData, GBufferCData, deviceZ);
			}			
		
			float4 main(VStoFS input) : SV_Target0
			{
				GBufferData gBufferData = getGBufferData(input.uv0);

				if(gBufferData.worldNormal.w > 0.0f)
				{
					float3 cameraDir = normalize(input.screenDir);
					float3 worldPosition = input.screenDir * gBufferData.depth + gViewOrigin;
					
					LightData lightData = getLightData();
					return getLighting(worldPosition, input.uv0, gBufferData, lightData);
				}
				else
					return float4(0.0f, 0.0f, 0.0f, 0.0f);
			}
		
```

**Comment by BearishSun** [comment] 2017-01-13 15:25
Ah! DirectX compiler optimized out the gGBufferCTex uniform because its value isn't used anywhere.

This is a non-issue then, and your warning should disappear after your shader code starts using the GBufferData.pbr value you decode from gGBufferCTex.

**Comment by dragonCASTjosh** [comment] 2017-01-13 15:28
ah i didnt even know what was a thing.

**Closed** 2017-06-14 09:02 UTC
