### ISSUE TITLE
Unable to minimize editor window from task bar

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#277] opened 2019-04-22 05:01 UTC
Like the title says. Left clicking on the icon on the task bar when the editor is focused does not minimize the editor window as expected.

**Comment by BearishSun** [comment] 2019-04-24 08:57
This one is not high priority, but interesting. It's something Windows should do under the hood, I wonder what we're doing that's breaking it.

**Comment by ReDucTor** [comment] 2019-05-06 12:25
@jayrulez this appears to be a duplicate of #54 ?

**Comment by BearishSun** [comment] 2019-05-06 14:18
Indeeds, looks like a duplicate. I'll close this one.

**Closed by BearishSun** 2019-05-06 14:18 UTC
