### ISSUE TITLE
The build function does  not work correctly

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#203] opened 2018-04-28 07:16 UTC
i created a scene and saved as test.prefab. 
 then i use build window to build and selected the test.prefab as the main scene.
click the build button.
The progress bar is not going.

**Comment by BearishSun** [comment] 2018-04-28 14:37
This is a known issue, duplicate of #162.

**Closed by BearishSun** 2018-04-28 14:37 UTC
