### ISSUE TITLE
EDITOR: DRAG&DROP of model leaves instances on the window border that can't be removed.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#116] opened 2017-12-17 02:12 UTC
BUILD DATE: (16 december 2017)
Problem description:
By dragging a model out of the ressource window onto the scene window and going over a border of this window will leave a object instance in the scene that can't be selected and|or removed.

![pistols](https://user-images.githubusercontent.com/13395943/34075958-a585f770-e2a5-11e7-884a-8030f37c985c.jpg)

Note: Once this happen, if we remove any object from the hierarchy windows, the instance will also not be removed from the scene window and will not be selectable after.

**Comment by BearishSun** [comment] 2017-12-27 10:42
I am unable to reproduce this issue. Could you try reproducing it again on a fresh project? Perhaps it is something that was fixed recently. Otherwise, if it still happens, there must be something we are doing differently. Also, some of these issues could be caused by some earlier problem, always check the log (even if it doesn't cause a crash).

**Comment by christianclavet** [comment] 2017-12-28 01:19
Retested with my new build of today on DX11 (12/27/17) and I am also unable to replicate the issue. Perhaps I would need to check with OpenGl? (I had a GL build when this occurred)

**Comment by BearishSun** [comment] 2017-12-28 08:22
I have actually tried with both DirectX and OpenGL, and it's not happening. I'll close the issue for now and we can re-open when/if the problem re-appears.

**Closed by BearishSun** 2017-12-28 08:22 UTC
