### ISSUE TITLE
Editor crash when creating material with Vulkan backend

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#313] opened 2019-07-09 14:29 UTC
The exception message:

```
Exception thrown at 0x00007FFE9029A839 in Banshee3D.exe: Microsoft C++ exception: VK::Exception at memory location 0x00000047449FEAD0.
Exception thrown at 0x00007FFE9029A839 in Banshee3D.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFE9029A839 in Banshee3D.exe: Microsoft C++ exception: VK::Exception at memory location 0x00000047449FEAD0.
Exception thrown at 0x00007FFE9029A839 in Banshee3D.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFE9029A839 in Banshee3D.exe: Microsoft C++ exception: VK::Exception at memory location 0x00000047449FEAD0.
[ERROR] Cannot convert pixels between buffers of different sizes.
		 in void __cdecl bs::PixelUtil::bulkPixelConversion(const class bs::PixelData &,class bs::PixelData &) [D:\banshee\BansheeEngine\Source\bsf\Source\Foundation\bsfCore\Image\BsPixelUtil.cpp:1927]

Exception thrown at 0x00007FFE2AC17667 (igvk64.dll) in Banshee3D.exe: 0xC0000005: Access violation reading location 0x0000000100000000.
```

I was running a release build.

**Comment by BearishSun** [comment] 2019-07-11 06:47
Thanks for the report. This one should be fixed on latest.

**Closed by BearishSun** 2019-07-11 06:47 UTC
Labels: EXT, type: bug

**Comment by christianclavet** [comment] 2019-07-18 00:40
Thanks for reporting! It happen to me, but I didn't had the time to report since I was testing the animation window.  The build I had in the weekend seem ok and I was not able to reproduce it.
