### ISSUE TITLE
[EDITOR] Crash on start - Win 8.1

### ISSUE THREAD

**Issue by 690fps** [BearishSun/BansheeEngine#235] opened 2018-07-14 05:56 UTC
I downloaded Editor binaries v0.4.0 (Windows x64)
Getting an error when starting Editor on Windows 8.1
VS2015 and VS2017 are installed

```
Fatal error occurred and the program has to terminate!
Unhandled exception at 0x140703303818232. Code 0x3765269347.
Stack trace: 
0x140703303818232 Module[KERNELBASE.dll]
0x140737468967712 Module[VCRUNTIME140.dll]
0x140703347386979 Module[ntdll.dll]
0x140737363065793 Module[BansheeOIS.dll]
BansheeEngine::InputHandlerOIS::InputHandlerOIS() - 0x140737363263044 File[bsinputhandlerois.cpp:93 (70)] Module[BansheeOISInput.dll]
loadPlugin() - 0x140737363279587 File[bsoisplugin.cpp:31 (0)] Module[BansheeOISInput.dll]
BansheeEngine::CoreApplication::loadPlugin() - 0x140737388978244 File[bscoreapplication.cpp:366 (5)] Module[BansheeCore.dll]
BansheeEngine::Application::onStartUp() - 0x140737385022968 File[bsapplication.cpp:53 (0)] Module[BansheeEngine.dll]
BansheeEngine::EditorApplication::onStartUp() - 0x140737391780308 File[bseditorapplication.cpp:83 (0)] Module[BansheeEditor.dll]
WinMain() - 0x140699019252065 File[bseditorexec.cpp:25 (0)] Module[BansheeEditorExec.exe]
__scrt_common_main_seh() - 0x140699019253310 File[exe_common.inl:255 (33)] Module[BansheeEditorExec.exe]
0x140703308453549 Module[KERNEL32.DLL]
0x140703346873572 Module[ntdll.dll]
```

Crash reports and system info:
[3. Win 8.1 Fatal error.zip](https://github.com/BearishSun/BansheeEngine/files/2194693/3.Win.8.1.Fatal.error.zip)

![14-07-2018 112036](https://user-images.githubusercontent.com/38181025/42721399-8ae82398-8764-11e8-9e78-d94b2be808c1.png)

**Comment by BearishSun** [comment] 2018-07-14 06:22
Hi. All reported issues need to be reproducible on the latest master build. v0.4.0 release is very old and quite likely this issue was already resolved.

**Comment by BearishSun** [comment] 2018-07-18 09:45
Closing due to old version it occurred on. If the issue still persists on master feel free to reopen the issue.

**Closed by BearishSun** 2018-07-18 09:45 UTC
