### ISSUE TITLE
Issue with default PBR shader with the roughness and metalness components.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#131] opened 2018-01-05 03:56 UTC
Hi, 

Was looking at the models inside banshee and it seem to me that the shader doesnt interpret the metalness and roughness component. The shader seem to process something but mostly like a black value (0,0,0) that would make the material smooth and reflect the environment. (Reflection Probe). 

Normal maps and albedo (with alpha) are processed correctly.

You can use this model for testing. This appear mostly with a reflection probe, everything look too reflective.
[Door.zip](https://github.com/BearishSun/BansheeEngine/files/1605519/Door.zip)

Also found out that If I want a dark scene, the Skybox picture must be total black. As the intensity is not interpreted by the Reflection Probe. 
 
For a test, use a model with all the textures, and the same model, with only the albedo and normal map applied.

Here is the environment that I use for the skybox (cylindrical cubemap)
![harbor_3_free_env](https://user-images.githubusercontent.com/13395943/34595180-d25abfd0-f1a3-11e7-99db-1c62b902d408.jpg)

**Comment by christianclavet** [comment] 2018-01-05 21:34
Thanks. I will have to create the pics and check more. But I had the SAME result with and without a reflection probe. The reflection probe made it much more apparent. Perhaps it's a project data corruption issue again. 3-4 projects now that I have to create and start as new because there something that strange like this that happen. Once I start a new project, seem to "fix" itself. But not tried yet doing it for this issue.

**Comment by christianclavet** [comment] 2018-01-06 04:06
Ok. Had the time to redo the testing. I think the "internal" folder data get corrupted. But the shader is ok, it's only something that "break up" what is sent to the shader.

Got the new build from the new code you added today. And gloss everywhere like theses 2 components where not present.  Here is a screen. The metal of the door should not shine like that and it's not looking metallic.
![bansheecapture](https://user-images.githubusercontent.com/13395943/34636272-957ad73a-f26b-11e7-95ab-503c6a2cced6.JPG)

Here what I've done:
- I exited Banshee, deleted the INTERNAL folder completely that was getting really big (almost 900Mb when the ressource were getting to 100Mb). 
- Restarted Banshee and reloaded the projet. Saw Banshee is re-importing everything. I deleted the scene that was not loading anymore as it is crashing Banshee if I try to double click on it to open it.
- Put back the skybox with the texture, and the reflection probe (spherical 500 unit)
- Put back the door model in the scene, then tried to put back the material. The door is now completely black. So the internal folder have something to do with the material data. 
- I created a new material with the same 4 textures and applied it to the model in the scene.
- Applied it back to the model and it's now working properly.
![redone](https://user-images.githubusercontent.com/13395943/34636310-8858c598-f26c-11e7-87af-a99e67e2bfe3.JPG)

My current conclusion is that something happen to the data in the material definition (material.asset file or internal folder, I don't know). I've had to create multiple project because of inexplicable behavior, and decided to start as new. But deleting the "internal" folder kinda fixe it. (Lose all informations and scenes but keep all the assets)

**Comment by BearishSun** [comment] 2018-01-06 08:51
Thanks for the additional information, sounds like a serious issue. Any chance you have the corrupted project that you can send me?

**Comment by christianclavet** [comment] 2018-01-06 21:26
Hi, Marko!

I've sent you a email on your gmail account with the link of a test project that got problems and that the size is still manageable to send.

It's a level that I downloaded and tested. If you work with the object, there seem to be no way to apply anything to it.

- Tried to change the position of the model. The model move, but when I click on another thing, the model get back to the original position.

- Tried to change the material on the model. The material is changed, but the moment, I click on something else, it revert back. 

If I start a new project and import it again, I can change the attributes. So there something in the project that do make the weird behavior.

**Comment by BearishSun** [comment] 2018-01-07 11:55
Thanks. Currently in a middle of something else but I plan on taking a look at this issue as soon as I'm done.

**Comment by BearishSun** [comment] 2018-01-10 21:35
The issue with not being able to modify the object in scene is due to the animation window being open and resetting things when it shouldn't. For now the solution is to keep the window closed until needed, and close it after. I'll get around to making a proper fix later on.

**Comment by christianclavet** [comment] 2018-01-10 22:36
OMG! You're right! All the project that I was not able to modify had the animation windows in the interface. I removed it and now I can change the properties again!

**Comment by christianclavet** [comment] 2018-01-15 16:04
Hi, 

PBR material is still new stuff to me...

I've done a lot of testing between 3D Coat and Banshee with the reflection probes, and seen that I've got now almost the same results, if I put higher values in the roughness map. Not a great amount. 

3D Coat seem to have lower reflections on the PBR materials, and Banshee a little more. I also saw that the reflectivity ramp up from value of 10 and lower. Using textures made of tints from Photoshop helped a lot figure this out.  So now, I think I've got a better "recipe" to get the textures looking better in Banshee. :)

Before, the ship hull look almost be made of silver:
![camera3](https://user-images.githubusercontent.com/13395943/34951256-ab5258e2-f9e3-11e7-9af8-3d76087be05c.JPG)

Yesterday after some tweaks on the hull. Is more of the wanted look. (made a screen desktop of it :) )
![montagebanshee](https://user-images.githubusercontent.com/13395943/34951313-cfc304b0-f9e3-11e7-9fda-7bf3e7c7e570.jpg)

**Comment by BearishSun** [comment] 2018-01-15 17:18
Looking great!

I still haven't managed to reproduce the issue with overly glossy surfaces. Are you still seeing that issue?

**Comment by christianclavet** [comment] 2018-01-15 19:19
As you warned me about, the environment lighting **IS** different in 3D coat than Banshee. 

The last tweaks I've done are fixing this problem with too much reflectivity. (As shown in the last pic) 

Now I know that I need to have little bit less of reflectivity when painting in 3D Coat and it would come all fine in Banshee.

**Closed** 2018-01-18 01:26 UTC
Labels: type: bug
