### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by AlexKR74** [BearishSun/BansheeEngine#85] opened 2017-07-20 07:42 UTC
Banshee Engine Log

System information

Banshee version: 0.4

OS version: Windows 6 64-bit

CPU vendor: GenuineIntel

CPU name: Intel(R) Core(TM) i3-3210 CPU @ 3.20GHz

CPU clock speed: 3192Mhz

CPU core count: 4

GPU: ATI Technologies Inc. AMD Radeon HD 6450

Log entries
Type   Description    
Error   A fatal error occurred and the program has to terminate!
- Error: InternalErrorException
- Description: OpenGL specified and manual uniform block buffer sizes don't match!
- In function: void __cdecl bs::ct::GLSLParamParser::buildUniformDescriptions(unsigned int,enum bs::GpuProgramType,struct bs::GpuParamDesc &)
- In file: d:\wh\banshee\bansheeengine-master\source\bansheeglrenderapi\source\bsglslparamparser.cpp:613

Stack trace: 
bs::CrashHandler::reportCrash() - 0x8791422679333 File[bswin32crashhandler.cpp:466 (0)] Module[BansheeUtility.dll]
bs::ct::GLSLParamParser::buildUniformDescriptions() - 0x8791477373052 File[bsglslparamparser.cpp:613 (151)] Module[BansheeGLRenderAPI.dll]
bs::ct::GLSLGpuProgram::initialize() - 0x8791477172018 File[bsglslgpuprogram.cpp:236 (0)] Module[BansheeGLRenderAPI.dll]
std::_Invoker_pmf_pointer::_Call() - 0x8791438793092 File[type_traits:1342 (0)] Module[BansheeCore.dll]
std::invoke() - 0x8791438812432 File[type_traits:1445 (0)] Module[BansheeCore.dll]
std::_Invoke_ret() - 0x8791438796596 File[type_traits:1476 (0)] Module[BansheeCore.dll]
std::_Call_binder,std::tuple >() - 0x8791438793870 File[functional:827 (0)] Module[BansheeCore.dll]
std::_Binder::operator()() - 0x8791438791864 File[functional:881 (136)] Module[BansheeCore.dll]
std::_Invoker_functor::_Call & __ptr64>() - 0x8791438792990 File[type_traits:1377 (0)] Module[BansheeCore.dll]
std::invoke & __ptr64>() - 0x8791438812878 File[type_traits:1445 (0)] Module[BansheeCore.dll]
std::_Invoke_ret & __ptr64>() - 0x8791438797042 File[type_traits:1462 (0)] Module[BansheeCore.dll]
std::_Func_impl,std::allocator,void>::_Do_call() - 0x8791438828373 File[functional:214 (0)] Module[BansheeCore.dll]
std::_Func_class::operator()() - 0x8791438718746 File[functional:280 (0)] Module[BansheeCore.dll]
bs::CoreObject::executeGpuCommand() - 0x8791438835595 File[bscoreobject.cpp:147 (0)] Module[BansheeCore.dll]
std::_Invoker_functor::_Call const & __ptr64,std::function),std::shared_ptr & __ptr64,std::function & __ptr64>() - 0x8791438792534 File[type_traits:1377 (0)] Module[BansheeCore.dll]
std::invoke const & __ptr64,std::function),std::shared_ptr & __ptr64,std::function & __ptr64>() - 0x8791438812290 File[type_traits:1445 (0)] Module[BansheeCore.dll]
std::_Invoke_ret const & __ptr64,std::function),std::shared_ptr & __ptr64,std::function & __ptr64>() - 0x8791438796438 File[type_traits:1476 (0)] Module[BansheeCore.dll]
std::_Call_binder const & __ptr64,std::function),std::tuple,std::function >,std::tuple >() - 0x8791438793680 File[functional:827 (0)] Module[BansheeCore.dll]
std::_Binder const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64>::operator()() - 0x8791438791672 File[functional:881 (136)] Module[BansheeCore.dll]
std::_Invoker_functor::_Call const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64> & __ptr64>() - 0x8791438792894 File[type_traits:1377 (0)] Module[BansheeCore.dll]
std::invoke const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64> & __ptr64>() - 0x8791438812782 File[type_traits:1445 (0)] Module[BansheeCore.dll]
std::_Invoke_ret const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64> & __ptr64>() - 0x8791438796946 File[type_traits:1462 (0)] Module[BansheeCore.dll]
std::_Func_impl const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64>,std::allocator,void>::_Do_call() - 0x8791438828261 File[functional:214 (0)] Module[BansheeCore.dll]
std::_Func_class::operator()() - 0x8791438718746 File[functional:280 (0)] Module[BansheeCore.dll]
bs::CommandQueueBase::playbackWithNotify() - 0x8791438774409 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]
bs::CoreThread::runCoreThread() - 0x8791439324740 File[bscorethread.cpp:119 (0)] Module[BansheeCore.dll]
std::_Invoker_pmf_pointer::_Call() - 0x8791439171956 File[type_traits:1342 (0)] Module[BansheeCore.dll]
std::invoke() - 0x8791439203632 File[type_traits:1445 (0)] Module[BansheeCore.dll]
std::_Invoke_ret() - 0x8791439179732 File[type_traits:1476 (0)] Module[BansheeCore.dll]
std::_Call_binder,std::tuple >() - 0x8791439172382 File[functional:827 (0)] Module[BansheeCore.dll]
std::_Binder::operator()() - 0x8791439170680 File[functional:881 (136)] Module[BansheeCore.dll]
std::_Invoker_functor::_Call & __ptr64>() - 0x8791439171710 File[type_traits:1377 (0)] Module[BansheeCore.dll]
std::invoke & __ptr64>() - 0x8791439203886 File[type_traits:1445 (0)] Module[BansheeCore.dll]
std::_Invoke_ret & __ptr64>() - 0x8791439179986 File[type_traits:1462 (0)] Module[BansheeCore.dll]
std::_Func_impl,std::allocator,void>::_Do_call() - 0x8791439267925 File[functional:214 (0)] Module[BansheeCore.dll]
std::_Func_class::operator()() - 0x8791419956314 File[functional:280 (0)] Module[BansheeUtility.dll]
bs::PooledThread::run() - 0x8791420529575 File[bsthreadpool.cpp:125 (0)] Module[BansheeUtility.dll]
std::_Invoker_pmf_pointer::_Call() - 0x8791420489572 File[type_traits:1342 (0)] Module[BansheeUtility.dll]
std::invoke() - 0x8791420501696 File[type_traits:1445 (0)] Module[BansheeUtility.dll]
std::_Invoke_ret() - 0x8791420494420 File[type_traits:1476 (0)] Module[BansheeUtility.dll]
std::_Call_binder,std::tuple >() - 0x8791420489838 File[functional:827 (0)] Module[BansheeUtility.dll]
std::_Binder::operator()() - 0x8791420489448 File[functional:881 (136)] Module[BansheeUtility.dll]
std::_Invoker_functor::_Call >() - 0x8791420489678 File[type_traits:1377 (0)] Module[BansheeUtility.dll]
std::invoke >() - 0x8791420501806 File[type_traits:1445 (0)] Module[BansheeUtility.dll]
std::_LaunchPad >,std::default_delete > > > >::_Execute() - 0x8791420492202 File[xthread:241 (0)] Module[BansheeUtility.dll]
std::_LaunchPad >,std::default_delete > > > >::_Run() - 0x8791420518525 File[xthread:250 (0)] Module[BansheeUtility.dll]
std::_LaunchPad >,std::default_delete > > > >::_Go() - 0x8791420515254 File[xthread:233 (0)] Module[BansheeUtility.dll]
std::_Pad::_Call_func() - 0x8791420513165 File[xthread:210 (0)] Module[BansheeUtility.dll]
0x8791503511996 Module[ucrtbased.dll]
0x8791503511059 Module[ucrtbased.dll]
0x2003068205 Module[kernel32.dll]
0x2005386561 Module[ntdll.dll]

**Comment by BearishSun** [comment] 2017-07-20 11:02
It appears the driver reported size of an uniform buffer doesn't match the size calculated by the engine, on your specific GPU/driver/OS combination.

Are you running the latest version of GPU drivers? If no, can you try updating the drivers and see if that changes things? Thanks.

**Comment by w-flo** [comment] 2017-12-27 15:20
I get this same error in ExampleGettingStarted on Ubuntu 17.10 using the mesa driver from Ubuntu 17.10's -proposed repo, obviously it only happens when compiling in Debug mode (as the check is in #if). After some debugging, I'm still not sure, but I think there might be a bug in the "check if buffer sizes match" code, not in the actual size computation.

The loop iterates over a map (keys: String values) and then assumes that the iteration takes place with increasing block index value (i.e. blockIdx is initialized to 0 and then incremented by 1 each iteration). According to some debug output that I've added to the code in a few places, this does not appear to be the case, as the block size calculation has blockname "PerObject" with block index 0, and blockname "PerCamera" with block index 1, but the check to compare calculated buffer sizes then has blockname "PerCamera" with block index 0. The assumption would probably hold only if blocks had their indices allocated in alphabetical order, which appears not to be the case using the mesa driver.

Since I don't really know about blocks, block names, block index, uniforms and OpenGL in general, I'll leave this here for someone else to interpret.

I've added this debug log:
```
curBlockDesc.blockSize = std::max(curBlockDesc.blockSize, gpuParam.cpuMemOffset + gpuParam.arrayElementStride * gpuParam.arraySize);

BS_CHECK_GL_ERROR();
LOGDBG(StringUtil::format("curBlockDesc blockSize: {0}, cpuMemOffset: {1}, arrayElementStride: {2}, arraySize: {3}, name {4}, blockindex {5}, blockName {6}, uniform index {7}.", curBlockDesc.blockSize, gpuParam.cpuMemOffset, gpuParam.arrayElementStride, gpuParam.arraySize, blockName, blockIndex, blockName, index));
```

And this:
```
LOGDBG(StringUtil::format("OpenGL block buffer size: {0}, manual block buffer size: {1}. Block index {2}, slot {3}, name{4}.", blockSize, (INT32)iter->second.blockSize, blockIdx, iter->second.slot, iter->second.name));
if ((INT32)iter->second.blockSize != blockSize)
	BS_EXCEPT(InternalErrorException, "OpenGL specified and manual uniform block buffer sizes don't match!");
```

Attaching debug output (most of it looking okay with bufferSize 24, but then there's that 68/140 mismatch at the end with PerCamera and PerObject buffer sizes seemingly mixed up):
[debug-log.txt](https://github.com/BearishSun/BansheeEngine/files/1589277/debug-log.txt)

No crash in Release mode, but I'm not sure if the rendering is correct, as the crocodile looks a little weird (sometimes 100% black texture, and sometimes textured in strange colors) and the background color sometimes changes when toggling full screen. Maybe that's intended. If not, it's probably a different issue.

**Comment by BearishSun** [comment] 2017-12-27 16:19
You are right, the index counting was comparing wrong buffers. I submitted a fix with df3857c7464515cda17898b576dec5bf95eaf9c9. I didn't manage to reproduce the issue myself, so there might be further problems.

Regarding the rendering problems. It is certainly not the intended behavior. If you don't mind opening another issue regarding that? I haven't tested using Mesa drivers so it's likely something related to that -
 possibly also related to uniform block sizes, and perhaps alignment of elements in them.

**Comment by w-flo** [comment] 2017-12-27 18:26
I think this solves this issue, thanks! I'm not 100% sure yet because I now have another Debug-mode-only exception, claiming that geometry shaders are not supported – and indeed, glxinfo only reports the "GL_EXT_geometry_shader" extension, not "GL_EXT_geometry_shader4", so maybe I have a driver issue that is also causing that other problem with weird rendering. I'll look into it and open another issue once I figured out what's going on there.

**Comment by w-flo** [comment] 2017-12-27 20:53
Okay, we can probably close this issue. After faking the geometry shader support check and then forcing Mesa to use OpenGL 4.4 (it would complain about pipeline 1 not meeting strict OpenGL ES 3.1 requirements otherwise) via MESA_GL_VERSION_OVERRIDE=4.4, I can now start example applications exception-free.

**Comment by BearishSun** [comment] 2017-12-28 08:23
That's good to hear, closing the issue.

**Closed by BearishSun** 2017-12-28 08:23 UTC
