### ISSUE TITLE
Building with visual studio 15.6.0 fails

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#179] opened 2018-03-07 07:10 UTC
(Updated)

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2903	'GetPropertyValue': symbol is neither a class template nor a function template (compiling source file C:\Users\Robert Campbell\Desktop\BansheeEngine\Source\BansheeFBXImporter\BsFBXPlugin.cpp)	BansheeFBXImporter	c:\users\robert campbell\desktop\bansheeengine\dependencies\fbxsdk\include\fbxsdk\core\fbxproperty.h	1215	

Building with 15.5.6 works fine on another machine and worked fine on this one before I updates VS.

**Comment by jayrulez** [comment] 2018-03-07 15:03
Updated

**Comment by BearishSun** [comment] 2018-03-07 15:32
Thanks, I'm able to reproduce the problem. The issue is in FBX SDK, which is a third party library. I have tried updating to the latest version but the issue is still there. 

Until they resolve this issue the workaround is to visit the file in question (`fbxproperty.h`), line 1215 and remove the `template` keyword before the call to `GetPropertyValue<T>`.

The line should look like this:
`return GetAnimationEvaluator()->GetPropertyValue<T>(*this, pTime, pForceEval);`

**Comment by BearishSun** [comment] 2018-03-07 16:09
Managed to work around it by disabling the `/permissive-` flag, fixed in 5b34da6d6f2f79f10b3dce0171e98b16855af80c,

**Closed by BearishSun** 2018-03-07 16:09 UTC
