### ISSUE TITLE
Selecting item in hierarchy causes stackoverflow exception in editor. 

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#202] opened 2018-04-22 18:53 UTC
I created a new scene,

Added an empty scene object then added a cube.

Clicking on the cube or scene object in the hierarchy reports a stackoverflow exception in the debug window.
[20180422_1346.zip](https://github.com/BearishSun/BansheeEngine/files/1935980/20180422_1346.zip)
![stackoverflow exception](https://user-images.githubusercontent.com/78807/39098715-96422412-4634-11e8-9356-ddb643bd4c7c.PNG)

**Comment by jayrulez** [comment] 2018-04-22 18:59
It's not just the hierarchy. This occurs in the library and scene windows also.

**Comment by jayrulez** [comment] 2018-04-22 19:00
Not sure how easy this might be to reproduce as it stopped after I created a material and dropped it onto the cube.

**Comment by BearishSun** [comment] 2018-04-22 19:09
Indeed, I cannot reproduce it. I imagine the actual problem was something that happened before the object was selected in the hierarchy. Something that left the editor in an invalid state and caused those errors upon selection. Can you remember what you did previous to creating the new scene with the box and selecting it?

The crash log you sent doesn't contain error messages in the screenshot. Any chance there's an error log with those messages? Perhaps the first error in that log can reveal the real issue.

**Comment by jayrulez** [comment] 2018-04-22 19:36
Before, I scaled the cube down on.

I am not able to reproduce it now. I had to close the editor though as the scene navigation started snapping when I tried to move around. Restarting the editor restored normal behaviour.

I'll try my best to reproduce this and capture all th logs.

**Comment by christianclavet** [comment] 2018-06-17 17:42
Try to do some undo/redo when you work in the scene. Seem an issue about using it. It happened to me once.

**Comment by BearishSun** [comment] 2019-05-20 18:33
I'll close this because the UndoRedo system went through a complete overhaul and this was likely resolved. I never managed to reproduce.

**Closed by BearishSun** 2019-05-20 18:33 UTC
