### ISSUE TITLE
The editor crashes when closing it

### ISSUE THREAD

**Issue by kushinn** [BearishSun/BansheeEngine#221] opened 2018-06-02 05:13 UTC
![1](https://user-images.githubusercontent.com/1787305/40871025-a48e4fe4-6666-11e8-870a-d3e54af3b278.png)

A fatal error occurred and the program has to terminate!
  - Error: InternalErrorException
  - Description: This method can only be accessed from the core thread.
  - In function: void __cdecl bs::throwIfNotCoreThread(void)
  - In file: f:\projects\engines\bansheeengine\source\bsf\source\foundation\bsfcore\corethread\bscorethread.cpp:310

Stack trace: 
bs::CrashHandler::reportCrash() - 0x140721407203318 File[bswin32crashhandler.cpp:468 (0)] Module[bsf.dll]
bs::throwIfNotCoreThread() - 0x140721408467027 File[bscorethread.cpp:310 (147)] Module[bsf.dll]
bs::ct::CoreObject::~CoreObject() - 0x140721408477888 File[bscoreobjectcore.cpp:20 (0)] Module[bsf.dll]
bs::ct::Texture::~Texture() - 0x140721414826671 File[bstexture.h:358 (111)] Module[bsf.dll]
bs::ct::D3D11Texture::~D3D11Texture() - 0x140721727917127 File[bsd3d11texture.cpp:38 (34)] Module[bsfD3D11RenderAPI.dll]
bs::ct::D3D11Texture::`scalar deleting destructor'() - 0x140721727921098 Module[bsfD3D11RenderAPI.dll]
bs::bs_delete<bs::ct::D3D11Texture,bs::GenAlloc>() - 0x140721727881583 File[bsmemoryallocator.h:269 (0)] Module[bsfD3D11RenderAPI.dll]
std::_Ref_count_resource_alloc<bs::ct::D3D11Texture * __ptr64,void (__cdecl*)(bs::ct::D3D11Texture * __ptr64),bs::StdAlloc<bs::ct::D3D11Texture,bs::GenAlloc> >::_Destroy() - 0x140721727889000 File[memory:1017 (0)] Module[bsfD3D11RenderAPI.dll]
std::_Ref_count_base::_Decref() - 0x140721584511625 File[memory:895 (0)] Module[bsfRenderBeast.dll]
std::_Ptr_base<bs::ct::Texture>::_Decref() - 0x140721584511160 File[memory:1169 (0)] Module[bsfRenderBeast.dll]
std::shared_ptr<bs::ct::Texture>::~shared_ptr<bs::ct::Texture>() - 0x140721584463590 File[memory:1461 (0)] Module[bsfRenderBeast.dll]
`dynamic atexit destructor for 'bs::ct::RendererTextures::defaultIndirect''() - 0x140721586493818 Module[bsfRenderBeast.dll]
0x140721737173751 Module[ucrtbased.dll]
0x140721737172293 Module[ucrtbased.dll]
0x140721737172554 Module[ucrtbased.dll]
0x140721737174177 Module[ucrtbased.dll]
__scrt_dllmain_uninitialize_c() - 0x140721586373993 File[utility.cpp:400 (0)] Module[bsfRenderBeast.dll]
dllmain_crt_process_detach() - 0x140721586378596 File[dll_dllmain.cpp:107 (0)] Module[bsfRenderBeast.dll]
dllmain_crt_dispatch() - 0x140721586378071 File[dll_dllmain.cpp:138 (30)] Module[bsfRenderBeast.dll]
dllmain_dispatch() - 0x140721586378958 File[dll_dllmain.cpp:211 (19)] Module[bsfRenderBeast.dll]
_DllMainCRTStartup() - 0x140721586379329 File[dll_dllmain.cpp:253 (0)] Module[bsfRenderBeast.dll]
0x140722660393283 Module[ntdll.dll]
0x140722660444917 Module[ntdll.dll]
0x140722660444600 Module[ntdll.dll]
0x140722614743450 Module[KERNEL32.DLL]
0x140721737171162 Module[ucrtbased.dll]
0x140721737171097 Module[ucrtbased.dll]
0x140721737171926 Module[ucrtbased.dll]
monoeg_assertion_message() - 0x140721313097433 File[goutput.c:138 (0)] Module[mono-2.0-sgen.dll]
check_obj_not_in_domain_callback() - 0x140721319100070 File[sgen-debug.c:876 (56)] Module[mono-2.0-sgen.dll]
sgen_mark_normal_gc_handles() - 0x140721319187789 File[sgen-gchandles.c:130 (0)] Module[mono-2.0-sgen.dll]
sgen_scan_for_registered_roots_in_domain() - 0x140721319059925 File[sgen-debug.c:933 (0)] Module[mono-2.0-sgen.dll]
mono_gc_clear_domain() - 0x140721315262365 File[sgen-mono.c:883 (0)] Module[mono-2.0-sgen.dll]
mono_domain_free() - 0x140721313425297 File[domain.c:1091 (0)] Module[mono-2.0-sgen.dll]
unload_thread_main() - 0x140721313414540 File[appdomain.c:2607 (0)] Module[mono-2.0-sgen.dll]
start_wrapper_internal() - 0x140721314634534 File[threads.c:994 (0)] Module[mono-2.0-sgen.dll]
start_wrapper() - 0x140721314634970 File[threads.c:1053 (19)] Module[mono-2.0-sgen.dll]
0x140722614710324 Module[KERNEL32.DLL]
0x140722660644177 Module[ntdll.dll]

**Comment by BearishSun** [comment] 2018-06-02 09:13
This a duplicate of #185. It's the same issue as the crash on exit with Vulkan, it's just that the crash ends up in whatever RenderAPI is currently used, but it's a red herring and not related to that at all. Same crash will happen with OpenGL.

**Closed by BearishSun** 2018-06-02 09:13 UTC
