### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by zEh-** [BearishSun/BansheeEngine#174] opened 2018-02-23 20:49 UTC
Opening the current prebuilt editor results in an exception without even doing something. It doesn't happen immediately all the time but sometimes delayed. Couldn't find a similiar issue.
Win10, Ryzen 7 1700X, GTX1060

![exception](https://user-images.githubusercontent.com/1783655/36616262-6ba1b5de-18e3-11e8-9cf0-dcf120ce551a.png)

Unhandled exception at 0x140703572870020. Code 0x2147483651.

Stack trace:
0x140703572870020 Module[ucrtbase.dll]
BansheeEngine::AnimationManager::waitUntilComplete() - 0x140737127730364 File[bsanimationmanager.cpp:479 (0)] Module[BansheeCore.dll]
BansheeEngine::RenderBeast::renderAllCore() - 0x140737370644773 File[bsrenderbeast.cpp:568 (0)] Module[RenderBeast.dll]
BansheeEngine::CommandQueueBase::playbackWithNotify() - 0x140737125273707 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]
BansheeEngine::CommandQueueBase::playback() - 0x140737125273927 File[bscommandqueue.cpp:141 (0)] Module[BansheeCore.dll]
BansheeEngine::CommandQueueBase::playbackWithNotify() - 0x140737125273707 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]
BansheeEngine::CoreThread::runCoreThread() - 0x140737125329201 File[bscorethread.cpp:124 (0)] Module[BansheeCore.dll]
BansheeEngine::PooledThread::run() - 0x140737351551772 File[bsthreadpool.cpp:125 (0)] Module[BansheeUtility.dll]
std::_LaunchPad<std::unique_ptr<std::tuple<std::_Binder<std::_Unforced,void (__cdecl BansheeEngine::PooledThread::*)(void) __ptr64,BansheeEngine::PooledThread * __ptr64 const> >,std::default_delete<std::tuple<std::_Binder<std::_Unforced,void (__cdecl BansheeEngine::PooledThread::*)(void) __ptr64,BansheeEngine::PooledThread * __ptr64 const> > > > >::_Run() - 0x140737351557701 File[xthread:250 (0)] Module[BansheeUtility.dll]
std::_Pad::_Call_func() - 0x140737351549705 File[xthread:210 (0)] Module[BansheeUtility.dll]
0x140703572547717 Module[ucrtbase.dll]
0x140703615623140 Module[KERNEL32.DLL]
0x140703634812817 Module[ntdll.dll]

**Comment by BearishSun** [comment] 2018-02-23 20:56
The prebuilt version is very old. This particular issue has been resolved on the master branch. Duplicate of #49.

**Closed by BearishSun** 2018-02-23 20:56 UTC
