### ISSUE TITLE
Crash wehen execute a compute task

### ISSUE THREAD

**Issue by TumblerSGQ** [BearishSun/BansheeEngine#331] opened 2019-10-10 12:37 UTC
![image](https://user-images.githubusercontent.com/12553991/66569271-c17b8000-eb9d-11e9-9c8f-579884024992.png)

GraphicCard: Intel HD630

**Comment by BearishSun** [comment] 2019-10-18 05:39
Please post the crash log. There is not enough information in that screenshot for me to determine what would be the cause.

**Comment by TumblerSGQ** [comment] 2019-10-18 06:22
It crashes in the Graphic Driver

**Comment by BearishSun** [comment] 2019-10-18 08:34
Thanks. In that case I'll close this issue and we can track it in #324.

**Closed by BearishSun** 2019-10-18 08:34 UTC
Labels: need more information, type: bug
